# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Artist.create([
  {first_name: "Alex", last_name:"Leblanc", bio:  %{<p> Natif de Montréal, Alex Leblanc vivra son enfance en Outaouais, dans la région de la Petite-Nation. Très jeune, l'attrait de la photographie se manifeste grâce à une mère complice qui prend plaisir à mettre en photos les faits et gestes de son fils. Encouragé par celle-ci, le jeune Alex manie habilement un appareil 35 mm qui le propulse dans l'univers de la créativité.</p>
<p>Quelques années plus tard, il obtient un diplôme d'études collégiales en photographie à la Cité collégiale d'Ottawa. Des études d'arts visuels à cette même institution l'initie aux pratiques multidisciplinaires et médiatiques.</p>
<p>Depuis huit ans, Alex Leblanc enseigne la photo et l'art médiatique au niveau secondaire. Parallèlement à son enseignement, il poursuit sans relâche sa démarche artistique, dont l'intérêt premier converge vers la théâtralité en photographie.</p>
<p>« Puisque l'être humain est incapable de maîtriser pleinement son univers sensoriel, il tente de recréer les facettes. Par le truchement de documents photographiques qui d'ailleurs ne sont qu'un pâle reflet de la réalité, il voudra reconstituer cet univers sensoriel, mais en vain. Il ne peut réussir,

car la nature même de la documentation est avant tout subjective; elle véhicule d'abord l'intention de celui qui la perçoit ».</p>}, city: "Gatineau", first_piece: "Cabot", second_piece: "Couleurs de Marie"},
  {first_name: "André", last_name:"Paquin", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Morceaux d’été", second_piece: "Temps d’automne"},
  {first_name: "Cécile", last_name: "Boucher", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Pile ou Face", second_piece: "Pile ou Face (Détail)"},
  {first_name: "Dominique", last_name: "Laurent", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Madeleine"},
  {first_name: "Doris", last_name: "Lamontagne", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Bio décryptage"},
  {first_name: "Frances", last_name: "Caswell-Routhier", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Vecteur 1", second_piece: "Vecteur 2"},
  {first_name: "Joan", last_name: "Rzadkiewicz", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Soirée lounger", second_piece: "Space view"},
  {first_name: "Joseph", last_name: "Muscat", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Eau brûlante", second_piece: "Lunarythme"},
  {first_name: "Jules", last_name: "Villemaire", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Deux mondes", second_piece: "Sympathie"},
  {first_name: "", last_name: "Lost Paradigm", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Un aller simple"},
  {first_name: "Martine", last_name: "Gilbert", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Inclassable", second_piece: "Les tricoteuses"},
  {first_name: "Patricia", last_name: "Pigeon", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Pourquoi?", second_piece: "Et encore Pourquoi?"},
  {first_name: "Paul", last_name: "Walty", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "À la va-vite", second_piece: "Et que ça saute"},
  {first_name: "Paula", last_name: "Franzini", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Rupture", second_piece: "Vision Nocturne"},
  {first_name: "Raymond", last_name: "Aubin", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Dépanneur no 6", second_piece: "Je"},
  {first_name: "Claire", last_name: "Cloutier", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Vega la bleue"},
  {first_name: "Denis", last_name: "Leclerc", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "System of the World"},
  {first_name: "Louis", last_name: "Godbout", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Doux sauvage", second_piece: "Les Eaux"},])