# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Artist.create([
  {first_name: "Alex", last_name:"Leblanc", bio:  %{<p> Natif de Montréal, Alex Leblanc vivra son enfance en Outaouais, dans la région de la Petite-Nation. Très jeune, l'attrait de la photographie se manifeste grâce à une mère complice qui prend plaisir à mettre en photos les faits et gestes de son fils. Encouragé par celle-ci, le jeune Alex manie habilement un appareil 35 mm qui le propulse dans l'univers de la créativité.</p>
<p>Quelques années plus tard, il obtient un diplôme d'études collégiales en photographie à la Cité collégiale d'Ottawa. Des études d'arts visuels à cette même institution l'initie aux pratiques multidisciplinaires et médiatiques.</p>
<p>Depuis huit ans, Alex Leblanc enseigne la photo et l'art médiatique au niveau secondaire. Parallèlement à son enseignement, il poursuit sans relâche sa démarche artistique, dont l'intérêt premier converge vers la théâtralité en photographie.</p>
<p>« Puisque l'être humain est incapable de maîtriser pleinement son univers sensoriel, il tente de recréer les facettes. Par le truchement de documents photographiques qui d'ailleurs ne sont qu'un pâle reflet de la réalité, il voudra reconstituer cet univers sensoriel, mais en vain. Il ne peut réussir,

car la nature même de la documentation est avant tout subjective; elle véhicule d'abord l'intention de celui qui la perçoit ».</p>}, city: "Gatineau", first_piece: "Cabot", second_piece: "Couleurs de Marie"},
  {first_name: "André", last_name:"Paquin", bio: %{<p>Passionné de photo depuis 40 ans, je suis passé au numérique il y a 10 ans. Diplômé en photo de l’école Ste-Ursule en 1976, bachelier en Arts à l’UQO en 1996, mon parcours a emprunté diverses avenues, non seulement comme photographe mais aussi artiste, commissaire, jury, documentariste, archiviste, membre d’associations d’artistes ou de photographes. Mes photos font partie de collections privées ou publiques et ont été vues en exposition au Canada et en Europe.</p>}, city: "Gatineau", first_piece: "Morceaux d’été", second_piece: "Temps d’automne"},
  {first_name: "Cécile", last_name: "Boucher", bio: %{<p>Bachelière en arts visuels de l'Université du Québec, Cécile Boucher est boursière des Conseils des arts du Canada, de l’Ontario et du Conseil des arts et des lettres du Québec.</p>
<ul>
<li>Expositions individuelles et collectives au Canada, en Europe, au Japon, au Chili (Musée d’art contemporain de Santiago, Musée d’art contemporain de Valdivia), en Colombie, en Corée du Sud, à Lahore et à Islamabad, au Pakistan.</li>

<li>Comme artiste invitée : Exposition internationale d'estampes de Toruń (Pologne), BIECTR de Trois-Rivières (Québec), Union College, Schenectady, New York.</li>

<li>Prix : Triennale Internationale de Cracovie, BIMPE de Vancouver, L’art et le papier à Ottawa.</li>

<li>Prix du Conseil des arts et des lettres du Québec pour la création artistique en région.</li>

<li>Trois œuvres d’intégration à l’Institut de cardiologie d’Ottawa.</li>

<li>Publication : “Printmaking – A Contemporary Perspective”, par Paul Coldwell, Londres, UK.</li>

<li>Collections publiques et privées : Banque d’œuvres d’art du Canada, Bombardier, Loto-Québec, Labidéeclic, villes d’Ottawa et de Gatineau.</li>
</ul>}, city: "Gatineau", first_piece: "Pile ou Face", second_piece: "Pile ou Face (Détail)"},
  {first_name: "Dominique", last_name: "Laurent", bio: %{<p>Bachelière en arts de l’Université du Québec en Outaouais, Dominique Laurent mène en parallèle une carrière d’artiste professionnelle et de gestionnaire des arts à la Ville de Gatineau. À titre d’artiste, elle est récipiendaire de plusieurs mentions et prix et a reçu des bourses du Conseil des arts et des lettres du Québec et du Conseil des Arts de l’Ontario. Elle a participé à de nombreuses expositions collectives en Ontario et au Québec ainsi qu’au Chili et en Slovaquie. Son intérêt pour les divers champs et pratiques artistiques est à la source de sa multidisciplinarité.</p>}, city: "Gatineau", first_piece: "Madeleine"},
  {first_name: "Doris", last_name: "Lamontagne", bio: %{<p>J’ai fait mes études en Arts plastiques au Cegep de Ste-Foy, puis j’ai poursuivi un Bac en communications visuelles à l’université Laval et à l’université de l’Alberta à Edmonton. Après mon Bac, j’ai travaillé en design à Edmonton pendant trois ans puis je me suis établie à Montréal où j’ai ouvert un studio de design qui a été en opération pendant plus de 8 ans. Cette entreprise d’affaire m’a valu le prix Banque Nationale pour jeunes entrepreneur en 1991.</p>
<p>De Montréal, je suis allée vivre à Pittsburgh PA, où avant de poursuivre une maitrise en design visuel et interaction à l’université Carnegie Mellon, j’ai enseigné le design graphique numérique à l’Institut des Arts de Pittsburgh. À l’obtention de ma maitrise, je me suis établie à Ottawa où j’ai travaillé comme chercheuse en design visuel et d’interaction pour le laboratoire de recherche de Nortel Telecom. Pendant ces cinq ans, j’ai obtenu deux brevets d’invention : un pour la conception d’un système de vidéo conférence adapté à la télémédecine, l’autre pour une interface d’écran tactile intégrée aux technologies multimédias (Multi-service user interface US 6313853 B1).</p>
<p>
Après Nortel, j’ai opté pour un retour aux arts visuels et je me consacre à ma création artistique en arts photographiques et numériques. Depuis 10 ans, j’expose mes œuvres dans différentes galeries de la région ainsi qu’aux États-Unis. J’ai été récipiendaire de bourses du Conseil des Arts des arts de l’Ontario et j’ai participé à différents jurys d’exposition. Je suis active avec différents groupes artistiques (Voix Visuelle, Galerie SAW, BRAVO CARFAC). Je participe régulièrement à des discussions et conférences sur l’avenir des arts : Sommet sur les arts visuels, table-ronde, Ottawa 2008, Conférence des collectifs et des centres d’artistes autogérés, Ottawa 2008, Construction créative symposium international, Ottawa 2008, Innovation Ottawa 2011, Creative Cities Summit: Recalculating Culture in a Digital World 2013).</p>}, city: "Gatineau", first_piece: "Bio décryptage"},
  {first_name: "Frances", last_name: "Caswell-Routhier", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Vecteur 1", second_piece: "Vecteur 2"},
  {first_name: "Joan", last_name: "Rzadkiewicz", bio: %{<p>Parallèlement à la composition numérique, ses installations se concentrent vers une exploration de l’espace et des matériaux à l’égard d’objets vernaculaires placés dans le contexte d’une observation philosophique. Ses œuvres ont été présentées dans de nombreuses expositions en Amérique du nord, ainsi qu’en Europe et au Cuba. Ses essais ont été publiés dans des revues et catalogues, notamment ETC Montréal art contemporain. Récipiendaire en 2008 de la bourse Fondation Pollock-Krasner, son travail à été également soutenu par l’Association des Collèges et des Universités du Canada durant un séjour à Budapest en lien avec l’Académie de Beaux-arts de l’Hongrie en 1989-90.</p>}, city: "Gatineau", first_piece: "Soirée lounger", second_piece: "Space view"},
  {first_name: "Joseph", last_name: "Muscat", bio: %{<p>Diplomé en arts et arts-visuels de l'universite de York, Toronto, Aix-Marseilles et du College des Beaux'arts de l"ontario.</p>
<p>Peintre, photographe depuis 1981; exposé au Canada, en Europe et aux États-Unis au milieu public et commerciale; representé par David Kaye Gallery, Toronto, par Shayna Laing Art International à Montreal et par Danielle Wohl Fine Arts à Palo Alto, Californie.</p>
<p>
Président de Propeller Gallery, Toronto et membre du conseil d’administration du Toronto Outdoor Art Exhibition. Membre fondateur de BRAVO et du Labo d'art.</p>
<p>Professeur d'arts visuels au Conseil Scolaire de Toronto - autrefois conférencier à la faculté d'architecture de l'université de Toronto.</p>}, second_piece: "Lunarythme"},
  {first_name: "Jules", last_name: "Villemaire", bio: %{<p>De plus de trente ans, Jules Villemaire fait corps avec sa caméra pour tenter de révéler, dans la capture de brefs instants, l’émotion qui n’est pas dite, le plaisir discret ou la douleur enfouie. Ses études l’amènent d’abord à s’intéresser à une forme de reportage social, dans les traces de deux grands noms dont il cite volontiers l’inspiration, Diane Arbus et Cartier-Bresson.</p>
    <p>L’une de ses premières expositions, sur Le travailleur forestier du Nord de l’Ontario, illustre bien cet intérêt. Il inspirera par la suite d’autres recherches du même type, avec Les oubliés / No names (1998), une série de portaits en studio de personnages sans-abri. Également, cette période l’amène à produire trois expositions de portraits de femmes, Passé/Futur en 1983, Un moment particulier en 1985 et ….De connivence (2002), une très belle exposition juxtaposant deux portraits de femmes. </p>
    <p>Aspiré par le tourbillon culturel qui entraîne sa génération, Jules se glisse dans les coulisses de la création artistique et devient aussi, pendant près de deux décennies, le principal témoin photographique, « l’œil », de l’Ontario français. Une génération en scène, publié aux Éditions Prise de Parole (1992), témoigne de cet engagement. Jules Villemaire s’affirme comme l’observateur privilégié, à la fois membre et spectateur, des manifestations artistiques – théâtrales et musicales notamment - qui marquent toute cette époque. </p>
    <p>La venue du numérique transforme alors son rapport à l’image, sans changer toutefois ses thèmes de prédilection. Lui ouvrant la porte à toutes formes de montage, cette nouvelle technique le conduit à extrapoler dans des formes de plus en plus ambitieuses (photos géantes, fresques) les sujets de ses expositions antérieures. Ainsi naît l’exposition Corps à corps (2001) puis, dans sa foulée, plusieurs montages réalisés pour l’exposition Art-en-Bourget (2001-2005), enfin une installation-performance, J’interpelle (2009), réalisant une performance au sein d’un montage photographique.</p>}, city: "Gatineau", first_piece: "Deux mondes", second_piece: "Sympathie"},
  {first_name: "", last_name: "Lost Paradigm", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Un aller simple"},
  {first_name: "Martine", last_name: "Gilbert", bio: %{<p>Née dans une ville minière du Nord-Ouest québécois, Martine Gilbert demeure et travaille en Outaouais. Durant les trois années de son baccalauréat, elle a expérimenté différents moyens d’expression : l’univers pictural, la sculpture, l’image numérique, la vidéo. Elle a obtenu une mention d’honneur pour son œuvre dans le cadre de l’exposition des finissants.</p>
<p>L’acquisition de connaissances techniques et théoriques à chaque projet d’exposition lui a permis de mieux cerner son potentiel. L’appareil photographique, l’ordinateur et le numériseur sont ses outils d’expression artistique. Observatrice attentive et passionnée des gestes de la quotidienneté, elle traque le fait divers, qu’elle transpose sous forme métaphorique. Les éléments constitutifs de ses empreintes numériques à la fois sobres et dépouillées reflet d'une réalité préexistante, priorise l'authenticité, le réel.</p>
<p>Depuis 1997, son approche artistique s’inscrit dans une démarche contemporaine ce qui l’ amènera à participer à plusieurs expositions de groupe au Québec, en Ontario, France, au Chili, au Musée d’art contemporain, à Santiago. En 2001, la ville d’Aylmer lui offre la possibilité de réaliser une œuvre publique. Dans le cadre l’exposition INTERNATIONALE DE L’ESTAMPE NUMÉRIQUES_Ottawa, en 2006, 2007 et 2012, le jury lui décerne deux fois un premier prix et un second.</p>}, city: "Gatineau", first_piece: "Inclassable", second_piece: "Les tricoteuses"},
  {first_name: "Patricia", last_name: "Pigeon", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Pourquoi?", second_piece: "Et encore Pourquoi?"},
  {first_name: "Paul", last_name: "Walty", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "À la va-vite", second_piece: "Et que ça saute"},
  {first_name: "Paula", last_name: "Franzini", bio: %{<p>Paula Franzini est née à New York et a vécu aux États-Unis et en Europe avant de s’installer en Québec. Elle a déménagé à Montréal en 1997, et plus récemment à Gatineau, près d’Ottawa. Elle est diplômée d’un doctorat en physique des particules élémentaires de l’Université de Stanford, et a travaillé dans les laboratoires de renommée mondiale en tant que physicienne avant de devenir artiste à temps plein (graveur et peintre). Elle a étudié la peinture et le dessin à Ar.Co, à Lisbonne, au Portugal et au Saidye Bronfman École des Beaux-Arts, à Montréal.</p>
<p>Depuis 1998, elle est membre du collectif Montréalais de l’art imprimé l’Atelier Circulaire, où elle a siégé au conseil d’administration pendant deux ans. Depuis 2009, elle est devenue un membre actif du centre d’artistes Voix Visuelle à Ottawa, où elle est actuellement vice-présidente, et où elle est également impliquée dans le travail de coordination et de soutien technique. Elle a participé à plusieurs expositions, tant au Canada qu’à l’étranger, et ses œuvres font partie de plusieurs collections privées et corporatives. Elle a reçu des bourses du Conseil des arts de l’Ontario pour la recherche et la création, et pour l’aide aux expositions. Son chemin multidisciplinaire – elle s’intéresse à maints sujets incluant les mathématiques, l’informatique, les sciences naturelles, la photographie, la littérature, et les langues – est une partie intégrante de son travail artistique.</p>}, city: "Gatineau", first_piece: "Rupture", second_piece: "Vision Nocturne"},
  {first_name: "Raymond", last_name: "Aubin", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Dépanneur no 6", second_piece: "Je"},
  {first_name: "Claire", last_name: "Cloutier", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Vega la bleue"},
  {first_name: "Denis", last_name: "Leclerc", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "System of the World"},
  {first_name: "Louis", last_name: "Godbout", bio: "This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later. This is the bio of the artist, to be added later.", city: "Gatineau", first_piece: "Doux sauvage", second_piece: "Les Eaux"},])